### PR TITLE
Adds User Rights Assignment tests

### LINKED ISSUE #35: Additional Test: UserRightsAssignment
When validating the security configuration of a server it is often necessary to test whether or not a particular account has certain user rights assigned to it or whether a particular user right is assigned to specific users.

We require a flexible implementation that will allow operators to write tests that test either for accounts or for user rights.
### Example

``` powershell
UserRightsAssignment ByAccount "BUILTIN\Users" { Should Not Match "SeServiceLogonRight" }
UserRightsAssignment ByRight "SeDebugPrivilege" { Should Be "BUILTIN\Administrators" }
```

### LINKED ISSUE #37: Additional Private Function: Test-RunAsAdmin
Some configurations can only be checked by a process running as admin.

We should have a repeatable, usable private function which handles this so public functions requiring the test do not need to duplicate it.

I'll be submitting this with my existing (and refactored) PR shortly.

### PR DESCRIPTION
**Pull request by michaeltlombardi**
- Fixes ticketmaster/poshspec#35
- Adds the private function `Test-RunAsAdmin`, closes Ticketmaster/poshspec#37
- Refactors AuditPolicy and UserRightsAssignment to use the `Test-RunAsAdmin` private function.
- Refactors UserRightsAssignment to place the private functions `Get-AccountsWithUserRight` and `Get-UserRightsGrantedToAccount` as well as the private type PS_LSA into a file in the private folder of the project, making UserRightsAssignment more readable/maintainable.

### CODE REVIEW

**Comment by michaeltlombardi** [comment]
It's a bit goofy, adding these tests, since it required adding a type into the public function. I reduced the surface area by chopping out all of the references I found to modifying the user rights assignments, leaving the ability only to retrieve them, never to modify them via tests.

VSCode can only do code folding via indentation so it looks a mess. I can refactor to use a separate private file if you want.

**Comment by cdhunt** [comment]
If it isn't a function a user would include in their tests, it should probably be in Private, but I think this is another very useful addition.

**Comment by michaeltlombardi** [comment]
I don't think users would access the functions or type directly; if they were going to do so, they'd probably want the full script/module and be able to set user rights as well as retrieve them.

Refactoring this to point to a private file containing the functions and type would definitely make `UserRightsAssignment.ps1` cleaner to read at the minor expense of having to include an additional private file for one test.

**Comment by michaeltlombardi** [comment]
Other tests (`AuditPolicy` and `Volume`) currently have private functions included inside them to make the expression itself less convoluted.

**Comment by michaeltlombardi** [comment]
@cdhunt: Refactored to use private functions/cleaner coding.

**Comment by michaeltlombardi** [comment]
@cdhunt: Is anything further required to get this merged?

**Comment by cdhunt** [comment]
No, I can merge it, however, I'm still looking at issues in some other areas before I publish a new version.

**Comment by michaeltlombardi** [comment]
No worries - anything I can help with?

**Pull request merged**
